import "./globals.css";
import type { Metadata } from "next";
import {Plus_Jakarta_Sans ,Inter } from "next/font/google";
import {Toaster} from "sonner";


const plus = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap" }
);
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <body className={plus.className}>

      {children}
      <Toaster />
      </body>
    </html>
  );
}
